Update sdlc_pipeline.yml

diff --git a/.github/workflows/sdlc_pipeline.yml b/.github/workflows/sdlc_pipeline.yml
--- a/.github/workflows/sdlc_pipeline.yml
+++ b/.github/workflows/sdlc_pipeline.yml
@@ -26,10 +26,9 @@ jobs:
 
       - name: Install in-toto
         run: |
-          python -m pip install --upgrade pip
-          pip install --break-system-packages in-toto
+          pip install in-toto
           echo "Verifying in-toto installation..."
-          python -m in_toto.run --version || echo "in-toto installation failed!"
+          python -m in-toto-run --version || echo "in-toto installation failed!"
 
       - name: Generate in-toto Key (For Demo - Should Be Secure in Production)
         run: |
